### ISSUE TITLE
Not working for me 

### ISSUE THREAD

**Issue by ashu8006kumar** [jofftiquez/angular-app-starter-pack#1]
It is showing a blank page with no errors

**Comment by jofftiquez** [comment]
@ashu8006kumar Hello, you might have missed the `/#/` on the end of the url? Like : `http://localhost/angular-app-starter-pack/#/`. Please let me know.

**Comment by ashu8006kumar** [comment]
Thank you , for your reply . I am using it without http now it is working :1st_place_medal:  .
Please close this issue . great work :+1:

**Comment by jofftiquez** [comment]
@ashu8006kumar Great! you can always post suggestions here. :) Thank you for using this repo.
